// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: uuids.kt
// Package: com.lightningkite.butterfly.bluetooth
import Foundation

public let notificationDescriptorUuid: UUID = UUID.fromString("00002902-0000-1000-8000-00805f9b34fb")

